version: "3.8"

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: Backend.Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./backend:/app
    working_dir: /app
    command: go run main.go

  frontend:
    build:
      context: .
      dockerfile: Frontend.Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: nginx -g "daemon off;"
